version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commadns:
      - chmod +x build.sh
      - ./build.sh int-test
      - ./build.sh deploy dev
      - ./build.sh acceptance-test