service: business-search-app

provider:
  name: aws
  runtime: nodejs10.x

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
