service: business-search-app

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "dynamodb:Scan"
      Resource: 
        - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants"
        - "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:*"


functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      restaurants_api: "https://ozk1g4x3w2.execute-api.us-east-1.amazonaws.com/dev/restaurants"

  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants/
          method: get
          authorizer: aws_iam
    environment:
      restaurants_table: restaurants

resources:
  Resources:
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurants
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10